cartes:
    type:     rest
    resource: ApiBundle\Controller\BarsController
articles:
    type:     rest
    resource: ApiBundle\Controller\ArticlesController
users:
    type:     rest
    resource: ApiBundle\Controller\UsersController
notifications:
    type:     rest
    resource: ApiBundle\Controller\NotificationsController
    prefix:   notifications